name: docker-push

on:
  # schedule runs
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # secrets from actions on Github
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{ defaultContext }}" # root directory
          push: true
          tags: pleabanshee/dating_app:latest
  deploy:
    needs: docker # only run this job when the docker job is finished
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - run: docker pull pleabanshee/dating_app:latest && docker run -d --name dating_app -p 8080:80 pleabanshee/dating_app:latest
