name: docker-push

on:
  # schedule runs
  workflow_dispatch:
  push:
    branches:
      - "main"
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} # Github action secret
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # secrets from actions on Github
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{ defaultContext }}" # root directory
          push: true
          tags: pleabanshee/dating_app:latest
  deploy:
    needs: docker # only run this job when the docker job is finished
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
